#!/usr/bin/env python3
"""
run_vtxz_dist.py  –  Orchestrator for vtxZDist HTCondor passes.

Usage:
    python3 run_vtxz_dist.py <config.py> --step 0          # generate files only
    python3 run_vtxz_dist.py <config.py> --step 1          # generate + submit
    python3 run_vtxz_dist.py <config.py> --step 0 --dry-run
    python3 run_vtxz_dist.py <config.py> --step 0 --set _Apply_cut=True

Steps:
    0 – Generate header (.h), macro (.C), condor job (.job), shell script (.sh)
        into output_directory/generated_macro/
    1 – Same as step 0, then submit with condor_submit

Generated files per pass (all inside output_directory/generated_macro/):
    <pass_name>_params.h          ← PassParams namespace header
    Run_vtxZDist_<pass>.C         ← patched macro (copy of template)
    run_job_<pass>.sh             ← patched shell script (copy of template)
    run_condor_<pass>.job         ← condor job description
"""

import argparse
import importlib.util
import os
import re
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path
from typing import Optional

# ── Make sure VtxZDistConfig is importable regardless of CWD ──────────
FRAMEWORK_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(FRAMEWORK_DIR))
from VtxZDistConfig import VtxZDistConfig

_HEADER_PLACEHOLDER = "header_to_be_replace"

# ─────────────────────────────────────────────────────────────────────────────
# Logging
# ─────────────────────────────────────────────────────────────────────────────

def log(msg: str, level: str = "INFO") -> None:
    tag = {"INFO": "[INFO]", "WARN": "[WARN]", "ERR": "[ERR ]", "STEP": "[STEP]"}.get(level, "[INFO]")
    print(f"{tag} {msg}")


# ─────────────────────────────────────────────────────────────────────────────
# Config loading + --set injection
# ─────────────────────────────────────────────────────────────────────────────

def load_config(config_path: str, pre_inject: Optional[dict] = None) -> VtxZDistConfig:
    """Load VtxZDistConfig from a .py file, optionally overriding top-level variables."""
    config_path = os.path.abspath(config_path)

    if pre_inject:
        with open(config_path) as f:
            src = f.read()
        for var, val in pre_inject.items():
            pattern = rf"^({re.escape(var)}\s*=\s*).*$"
            new_src, n = re.subn(pattern, rf"\g<1>{val}", src, flags=re.MULTILINE)
            if n == 0:
                log(f"--set: variable '{var}' not found in {config_path}", "WARN")
            else:
                log(f"--set: {var} = {val}")
            src = new_src
        import tempfile
        with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False) as tmp:
            tmp.write(src)
            tmp_path = tmp.name
        config_path = tmp_path

    spec = importlib.util.spec_from_file_location("_cfg_module", config_path)
    mod  = importlib.util.module_from_spec(spec)
    sys.path.insert(0, str(FRAMEWORK_DIR))  # so Config is importable from inside config
    spec.loader.exec_module(mod)

    if not hasattr(mod, "cfg"):
        raise AttributeError(f"Config file must define a variable 'cfg'. Not found in {config_path}")
    return mod.cfg


def parse_set_args(set_list: list) -> dict:
    result = {}
    for item in set_list:
        if "=" not in item:
            raise ValueError(f"--set argument must be VAR=VALUE, got: {item!r}")
        k, v = item.split("=", 1)
        result[k.strip()] = v.strip()
    return result


# ─────────────────────────────────────────────────────────────────────────────
# C++ helpers
# ─────────────────────────────────────────────────────────────────────────────

def _cpp_bool(v) -> str:
    return "true" if v else "false"

def _cpp_pair_bool_int(p) -> str:
    return f"{{{_cpp_bool(p[0])}, {p[1]}}}"


# ─────────────────────────────────────────────────────────────────────────────
# Header generation
# ─────────────────────────────────────────────────────────────────────────────

def generate_params_header(cfg: VtxZDistConfig, out_dir: str) -> str:
    """Write a C++ header with all PassParams constants. Returns the header path."""
    Path(out_dir).mkdir(parents=True, exist_ok=True)

    macro_name  = f"Run_vtxZDist_{cfg.pass_name}"
    header_name = f"{macro_name}_params.h"
    header_path = os.path.join(out_dir, header_name)

    # Default input filename (process 0)
    default_filename = cfg.input_file_name.format(process=0, run_num=cfg.run_number)

    lines = [
        "// ======================================================================",
        "// AUTO-GENERATED by run_vtxz_dist.py  –  DO NOT EDIT BY HAND",
        f"// Pass  : {cfg.pass_name}",
        f"// Notes : {cfg.notes or '(none)'}",
        "//",
        "// Re-generate by re-running Step 0:",
        "//   python3 run_vtxz_dist.py <config.py> --step 0",
        "// ======================================================================",
        "",
        "#pragma once",
        "#include <string>",
        "#include <utility>",
        "",
        "namespace PassParams {",
        "",
        "  // ── per-job defaults (used when running interactively) ──────────────",
        f'  const int         default_process_id      = 0;',
        f'  const int         default_run_num         = {cfg.run_number};',
        f'  const int         default_nevents         = {cfg.n_events};',
        f'  const std::string default_input_directory = "{cfg.input_directory}";',
        f'  const std::string default_input_filename  = "{default_filename}";',
        f'  const std::string default_output_directory= "{cfg.output_directory}";',
        "",
        "  // ── analysis parameters ─────────────────────────────────────────────",
        f'  const std::string output_file_name_suffix = "{cfg.output_file_name_suffix}";',
        f'  const bool        Apply_cut               = {_cpp_bool(cfg.Apply_cut)};',
        f'  const bool        ApplyVtxZReWeighting    = {_cpp_bool(cfg.ApplyVtxZReWeighting)};',
        f'  const std::pair<bool,int> ApplyEvtBcoFullDiffCut = {_cpp_pair_bool_int(cfg.ApplyEvtBcoFullDiffCut)};',
        f'  const bool        IsVtxZQACutKnown        = {_cpp_bool(cfg.IsVtxZQACutKnown)};',
        "",
        "}  // namespace PassParams",
        "",
    ]

    with open(header_path, "w") as f:
        f.write("\n".join(lines))

    log(f"Generated header  : {header_path}")
    return header_path


# ─────────────────────────────────────────────────────────────────────────────
# Template patching
# ─────────────────────────────────────────────────────────────────────────────

def copy_and_patch_macro(cfg: VtxZDistConfig, header_path: str, out_dir: str) -> str:
    """Copy template macro → out_dir, patch include + function name."""
    macro_name   = f"Run_vtxZDist_{cfg.pass_name}"
    template_src = os.path.join(cfg.macro_template_dir, "Run_vtxZDist_template.C")
    macro_dst    = os.path.join(out_dir, f"{macro_name}.C")

    if not os.path.isfile(template_src):
        raise FileNotFoundError(
            f"Template macro not found: {template_src}\n"
            f"Set cfg.macro_template_dir to the MacroGen directory."
        )

    Path(out_dir).mkdir(parents=True, exist_ok=True)
    shutil.copy2(template_src, macro_dst)
    log(f"Copied template   : {template_src}")
    log(f"             → {macro_dst}")

    abs_header = os.path.abspath(header_path)
    with open(macro_dst) as fh:
        src = fh.read()

    # Patch 1: include placeholder
    old_inc = f'#include "{_HEADER_PLACEHOLDER}"'
    new_inc = f'#include "{abs_header}"'
    if old_inc not in src:
        log(f"WARNING: placeholder '{old_inc}' not found in template.", "WARN")
    else:
        src = src.replace(old_inc, new_inc, 1)
        log(f"Patched include   : '{_HEADER_PLACEHOLDER}' → {abs_header}")

    # Patch 2: function name
    old_func = "void Run_vtxZDist_template("
    new_func = f"void {macro_name}("
    if old_func in src:
        src = src.replace(old_func, new_func, 1)
        log(f"Patched func name : 'Run_vtxZDist_template' → '{macro_name}'")
    else:
        log(f"WARNING: function signature not found in template.", "WARN")

    with open(macro_dst, "w") as fh:
        fh.write(src)

    return macro_dst


def copy_and_patch_shell(cfg: VtxZDistConfig, out_dir: str) -> str:
    """Copy run_job_template.sh → out_dir as run_job_<pass>.sh."""
    sh_name      = f"run_job_{cfg.pass_name}.sh"
    template_src = os.path.join(cfg.macro_template_dir, "run_job_template.sh")
    sh_dst       = os.path.join(out_dir, sh_name)

    if not os.path.isfile(template_src):
        raise FileNotFoundError(f"Shell template not found: {template_src}")

    shutil.copy2(template_src, sh_dst)
    os.chmod(sh_dst, 0o755)
    log(f"Copied shell      : {template_src}")
    log(f"             → {sh_dst}")
    return sh_dst


# ─────────────────────────────────────────────────────────────────────────────
# Condor job generation
# ─────────────────────────────────────────────────────────────────────────────

def generate_condor_job(cfg: VtxZDistConfig, job_file_path: str,
                        macro_path: str, sh_path: str) -> str:
    """Write the condor .job file."""
    macro_name = os.path.splitext(os.path.basename(macro_path))[0]
    sh_name    = os.path.basename(sh_path)   # relative – Initialdir = generated_dir
    gen_dir    = os.path.dirname(macro_path)

    # Translate Python {process:05d} placeholder → Condor macro
    condor_filename = re.sub(
        r"\{process:05d\}",
        "$INT(process_shift,%05d)",
        cfg.input_file_name
    )

    content = textwrap.dedent(f"""\
        Universe           = vanilla
        Initialdir         = {gen_dir}
        Executable         = {gen_dir}/{sh_name}
        PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
        concurrency_limits = CONCURRENCY_LIMIT_DEFAULT:{cfg.condor_concurrency_limit}
        request_memory     = {cfg.condor_request_memory}
        Priority           = {cfg.condor_priority}
        job_lease_duration = 86400

        runnumber          = {cfg.run_number}
        nEvents            = {cfg.n_events}
        input_directory    = {cfg.input_directory}
        job_offset         = {cfg.job_offset}
        process_shift      = $(Process) + $(job_offset)
        input_filename     = {condor_filename}
        output_directory   = {cfg.output_directory}
        macro_name         = {macro_name}

        Output             = $(output_directory)/cw_log/condor_$INT(process_shift,%05d).out
        Error              = $(output_directory)/cw_log/condor_$INT(process_shift,%05d).err
        Log                = $(output_directory)/cw_log/condor_$INT(process_shift,%05d).log
        Arguments          = "$INT(process_shift) $(runnumber) $(nEvents) $(output_directory) $(input_directory) $(input_filename) $(macro_name)"
        Queue {cfg.n_condor_jobs}
    """)

    Path(job_file_path).parent.mkdir(parents=True, exist_ok=True)
    with open(job_file_path, "w") as f:
        f.write(content)
    log(f"Wrote condor job  : {job_file_path}")
    return job_file_path


# ─────────────────────────────────────────────────────────────────────────────
# Step execution
# ─────────────────────────────────────────────────────────────────────────────

def run_cmd(cmd: str, dry: bool = False) -> int:
    if dry:
        log(f"  $ {cmd}")
        return 0
    log(f"  $ {cmd}")
    result = subprocess.run(cmd, shell=True)
    return result.returncode


def step_generate(cfg: VtxZDistConfig, dry: bool = False) -> None:
    log("── Step 0: Generate files ───────────────────────────────", "STEP")

    if not os.path.isdir(cfg.input_directory):
        log(f"Input directory not found: {cfg.input_directory}", "ERR")
        sys.exit(1)

    gen_dir = cfg.generated_dir()

    for d in [cfg.completed_dir(), cfg.condor_log_dir()]:
        if not dry:
            Path(d).mkdir(parents=True, exist_ok=True)
            log(f"Ensured directory : {d}")
        else:
            log(f"[dry] Would create: {d}")

    if not dry:
        hdr      = generate_params_header(cfg, gen_dir)
        macro    = copy_and_patch_macro(cfg, hdr, gen_dir)
        sh       = copy_and_patch_shell(cfg, gen_dir)
        job_file = os.path.join(gen_dir, f"run_condor_{cfg.pass_name}.job")
        generate_condor_job(cfg, job_file, macro, sh)
    else:
        macro_name = f"Run_vtxZDist_{cfg.pass_name}"
        log(f"[dry] Would generate header : {gen_dir}/{macro_name}_params.h")
        log(f"[dry] Would copy+patch macro → {gen_dir}/{macro_name}.C")
        log(f"[dry] Would copy shell      → {gen_dir}/run_job_{cfg.pass_name}.sh")
        log(f"[dry] Would write condor job: {gen_dir}/run_condor_{cfg.pass_name}.job")

    log("[STEP] File generation complete.")


def step_submit(cfg: VtxZDistConfig, dry: bool = False) -> None:
    step_generate(cfg, dry=dry)
    log("── Step 1: Submit condor jobs ───────────────────────────", "STEP")
    job_file = os.path.join(cfg.generated_dir(), f"run_condor_{cfg.pass_name}.job")
    rc = run_cmd(f"condor_submit {job_file}", dry=dry)
    if rc != 0:
        log(f"condor_submit failed (exit {rc})", "ERR")
        sys.exit(rc)
    log("Jobs submitted successfully.")


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="vtxZDist HTCondor pass orchestrator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent(__doc__),
    )
    parser.add_argument("config", help="Path to a config .py file (must define 'cfg').")
    parser.add_argument("--step", choices=["0", "1"], default="0",
                        help="0 = generate files only (default);  1 = generate + submit")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print what would be done without executing.")
    parser.add_argument(
        "--set", metavar="VAR=VALUE", action="append", default=[],
        help="Override a config variable before loading (e.g. --set _Apply_cut=True). "
             "Can be repeated.")

    args = parser.parse_args()
    dry  = args.dry_run

    if dry:
        log("DRY-RUN mode – no files will be written or submitted.", "WARN")

    pre_inject = parse_set_args(args.set) if args.set else None
    cfg = load_config(args.config, pre_inject)

    print(cfg.summary())

    if args.step == "0":
        step_generate(cfg, dry=dry)
    elif args.step == "1":
        step_submit(cfg, dry=dry)


if __name__ == "__main__":
    main()
