Universe           = vanilla
Initialdir         = /sphenix/user/ChengWei/INTT/INTTdNdEtaOO/GetNpartValue
Executable         = run_job.sh
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
concurrency_limits = CONCURRENCY_LIMIT_DEFAULT:100
request_memory     = 4GB
Priority           = 20
job_lease_duration = 86400

MC_name            = HIJING
nEvents            = -1
input_directory    = /sphenix/tg/tg01/commissioning/INTT/work/cwshih/Run25/dNdEtaOO/MC/20260608/HIJING_INTTSurveyOnly_CentralityScaleTest_customizedVertex/per5k
job_offset    = 0
process_shift      = $(Process) + $(job_offset) 
input_filename     = ntuple_per5k_$INT(process_shift,%05d).root
output_directory   = /sphenix/tg/tg01/commissioning/INTT/work/cwshih/Run25/dNdEtaOO/MC/20260608/HIJING_INTTSurveyOnly_CentralityScaleTest_customizedVertex/NpartValue

Output             = $(output_directory)/cw_log/condor_$INT(process_shift,%05d).out
Error              = $(output_directory)/cw_log/condor_$INT(process_shift,%05d).err
Log                = $(output_directory)/cw_log/condor_$INT(process_shift,%05d).log
Arguments          = "$INT(process_shift) $(MC_name) $(nEvents) $(output_directory) $(input_directory) $(input_filename)"
Queue 800