Universe           = vanilla
Initialdir         = /sphenix/user/ChengWei/INTT/INTTdNdEtaOO/PrepareAllDist/DataDrivenResolution/macro
Executable         = run_job.sh
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
concurrency_limits = CONCURRENCY_LIMIT_DEFAULT:1000
request_memory     = 4GB
Priority           = 20
job_lease_duration = 86400

runnumber          = 82391
nEvents            = -1
input_directory    = /sphenix/tg/tg01/commissioning/INTT/work/cwshih/Run25/dNdEtaOO/82391_new12_Centrality_20260210/EvtVtxZLeftRight/completed
job_offset    = 0
process_shift      = $(Process) + $(job_offset) 
input_filename     = Data_EvtVtxZLeftRight_FieldOn_BcoFullDiff_VtxZReco_LeftOnly_RightOnly_00082391_$INT(process_shift,%05d).root
output_directory   = /sphenix/tg/tg01/commissioning/INTT/work/cwshih/Run25/dNdEtaOO/82391_new12_Centrality_20260210/DataDrivenZResolution

Output             = $(output_directory)/cw_log/condor_$INT(process_shift,%05d).out
Error              = $(output_directory)/cw_log/condor_$INT(process_shift,%05d).err
Log                = $(output_directory)/cw_log/condor_$INT(process_shift,%05d).log
Arguments          = "$INT(process_shift) $(runnumber) $(nEvents) $(output_directory) $(input_directory) $(input_filename)"
Queue 200