Universe           = vanilla
Initialdir         = /sphenix/user/ChengWei/INTT/INTTdNdEtaOO/SelfProduction/macro/forMCINTTSurveyOnly/quick_check
Executable         = run_job.sh
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
concurrency_limits = CONCURRENCY_LIMIT_DEFAULT:100
request_memory     = 4GB
Priority           = 20
job_lease_duration = 86400

nEvents            = -1
input_directory    = /sphenix/lustre01/sphnxpro/production/run3oo/physics/ana537_nocdbtag_v001
input_filename     = I_am_cool

runnumber          = 37
job_offset    = 0
process_shift      = $(Process) + $(job_offset) 
output_directory   = /sphenix/tg/tg01/commissioning/INTT/work/cwshih/Run25/dNdEtaOO/MC/20260318/HIJING_INTTSurveyOnly_CentralityScaleTest_customizedVertex/quick_hist

Output             = $(output_directory)/cw_log/condor_$INT(process_shift,%05d).out
Error              = $(output_directory)/cw_log/condor_$INT(process_shift,%05d).err
Log                = $(output_directory)/cw_log/condor_$INT(process_shift,%05d).log
Arguments          = "$INT(process_shift) $(runnumber)"
Queue 4000