#!/usr/bin/env python3
"""
run_evt_vtxz_left_right.py - Orchestrator for EvtVtxZLeftRight HTCondor passes.

Usage:
    python3 run_evt_vtxz_left_right.py <config.py> --step 0
    python3 run_evt_vtxz_left_right.py <config.py> --step 1
    python3 run_evt_vtxz_left_right.py <config.py> --step 0 --dry-run
    python3 run_evt_vtxz_left_right.py <config.py> --step 0 --set _ClusAdcCut=30

Steps:
    0 - Generate header (.h), macro (.C), condor job (.job), shell script (.sh)
        into output_directory/generated_macro/
    1 - Same as step 0, then submit with condor_submit
"""

import argparse
import importlib.util
import os
import re
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path
from typing import Optional

FRAMEWORK_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(FRAMEWORK_DIR))
from EvtVtxZLeftRightConfig import EvtVtxZLeftRightConfig

_HEADER_PLACEHOLDER = "header_to_be_replace"


def log(msg: str, level: str = "INFO") -> None:
    tag = {"INFO": "[INFO]", "WARN": "[WARN]", "ERR": "[ERR ]", "STEP": "[STEP]"}.get(level, "[INFO]")
    print(f"{tag} {msg}")


def load_config(config_path: str, pre_inject: Optional[dict] = None) -> EvtVtxZLeftRightConfig:
    config_path = os.path.abspath(config_path)

    if pre_inject:
        with open(config_path) as f:
            src = f.read()
        for var, val in pre_inject.items():
            pattern = rf"^({re.escape(var)}\s*=\s*).*$"
            new_src, n = re.subn(pattern, rf"\g<1>{val}", src, flags=re.MULTILINE)
            if n == 0:
                log(f"--set: variable '{var}' not found in {config_path}", "WARN")
            else:
                log(f"--set: {var} = {val}")
            src = new_src
        import tempfile
        with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False) as tmp:
            tmp.write(src)
            config_path = tmp.name

    spec = importlib.util.spec_from_file_location("_cfg_module", config_path)
    mod = importlib.util.module_from_spec(spec)
    sys.path.insert(0, str(FRAMEWORK_DIR))
    spec.loader.exec_module(mod)

    if not hasattr(mod, "cfg"):
        raise AttributeError(f"Config file must define a variable 'cfg'. Not found in {config_path}")
    if not isinstance(mod.cfg, EvtVtxZLeftRightConfig):
        raise TypeError("'cfg' must be an EvtVtxZLeftRightConfig instance.")
    return mod.cfg


def parse_set_args(set_list: list) -> dict:
    result = {}
    for item in set_list:
        if "=" not in item:
            raise ValueError(f"--set argument must be VAR=VALUE, got: {item!r}")
        k, v = item.split("=", 1)
        result[k.strip()] = v.strip()
    return result


def _cpp_bool(v) -> str:
    return "true" if v else "false"


def _cpp_string(s: str) -> str:
    escaped = str(s).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _cpp_pair_double(p) -> str:
    return f"{{{p[0]}, {p[1]}}}"


def _cpp_pair_pair_double(p) -> str:
    return f"{{{{{p[0][0]}, {p[0][1]}}}, {{{p[1][0]}, {p[1][1]}}}}}"


def _default_input_filename(cfg: EvtVtxZLeftRightConfig) -> str:
    return cfg.input_file_name.format(process=0, run_num=cfg.run_number)


def _condor_input_filename(cfg: EvtVtxZLeftRightConfig) -> str:
    name = cfg.input_file_name
    name = name.replace("{process:05d}", "$INT(process_shift,%05d)")
    name = name.replace("{run_num:08d}", f"{cfg.run_number:08d}")
    name = name.replace("{run_num}", str(cfg.run_number))
    return name


def generate_params_header(cfg: EvtVtxZLeftRightConfig, out_dir: str) -> str:
    Path(out_dir).mkdir(parents=True, exist_ok=True)

    macro_name = f"Run_EvtVtxZLeftRight_{cfg.pass_name}"
    header_path = os.path.join(out_dir, f"{macro_name}_params.h")

    lines = [
        "// ======================================================================",
        "// AUTO-GENERATED by run_evt_vtxz_left_right.py - DO NOT EDIT BY HAND",
        f"// Pass  : {cfg.pass_name}",
        f"// Notes : {cfg.notes or '(none)'}",
        "//",
        "// Re-generate by re-running Step 0:",
        "//   python3 run_evt_vtxz_left_right.py <config.py> --step 0",
        "// ======================================================================",
        "",
        "#pragma once",
        "#include <string>",
        "#include <utility>",
        "",
        "namespace PassParams {",
        "",
        "  // -- per-job defaults (used when running interactively) -------------",
        "  const int         default_process_id      = 0;",
        f"  const int         default_run_num         = {cfg.run_number};",
        f"  const int         default_nevents         = {cfg.n_events};",
        f"  const std::string default_input_directory = {_cpp_string(cfg.input_directory)};",
        f"  const std::string default_input_filename  = {_cpp_string(_default_input_filename(cfg))};",
        f"  const std::string default_output_directory= {_cpp_string(cfg.output_directory)};",
        "",
        "  // -- analysis parameters --------------------------------------------",
        f"  const std::string output_file_name_suffix = {_cpp_string(cfg.output_file_name_suffix)};",
        f"  const std::pair<double,double> vertexXYIncm = {_cpp_pair_double(cfg.vertexXYIncm)};",
        f"  const bool IsFieldOn = {_cpp_bool(cfg.IsFieldOn)};",
        f"  const bool IsDCACutApplied = {_cpp_bool(cfg.IsDCACutApplied)};",
        f"  const std::pair<std::pair<double,double>,std::pair<double,double>> DeltaPhiCutInDegree = {_cpp_pair_pair_double(cfg.DeltaPhiCutInDegree)};",
        f"  const std::pair<std::pair<double,double>,std::pair<double,double>> DCAcutIncm = {_cpp_pair_pair_double(cfg.DCAcutIncm)};",
        f"  const int ClusAdcCut = {cfg.ClusAdcCut};",
        f"  const int ClusPhiSizeCut = {cfg.ClusPhiSizeCut};",
        f"  const bool PrintRecoDetails = {_cpp_bool(cfg.PrintRecoDetails)};",
        f"  const bool DrawEvtVtxZ = {_cpp_bool(cfg.DrawEvtVtxZ)};",
        f"  const bool RunInttBcoFullDiff = {_cpp_bool(cfg.RunInttBcoFullDiff)};",
        f"  const bool RunVtxZReco = {_cpp_bool(cfg.RunVtxZReco)};",
        f"  const bool RunTrackletPair = {_cpp_bool(cfg.RunTrackletPair)};",
        f"  const bool RunTrackletPairRotate = {_cpp_bool(cfg.RunTrackletPairRotate)};",
        f"  const bool HaveGeoOffsetTag = {_cpp_bool(cfg.HaveGeoOffsetTag)};",
        "",
        "}  // namespace PassParams",
        "",
    ]

    with open(header_path, "w") as f:
        f.write("\n".join(lines))

    log(f"Generated header  : {header_path}")
    return header_path


def copy_and_patch_macro(cfg: EvtVtxZLeftRightConfig, header_path: str, out_dir: str) -> str:
    macro_name = f"Run_EvtVtxZLeftRight_{cfg.pass_name}"
    template_src = os.path.join(cfg.macro_template_dir, "Run_EvtVtxZLeftRight_template.C")
    macro_dst = os.path.join(out_dir, f"{macro_name}.C")

    if not os.path.isfile(template_src):
        raise FileNotFoundError(
            f"Template macro not found: {template_src}\n"
            f"Set cfg.macro_template_dir to the MacroGen_LeftRight directory."
        )

    Path(out_dir).mkdir(parents=True, exist_ok=True)
    shutil.copy2(template_src, macro_dst)
    log(f"Copied template   : {template_src}")
    log(f"             -> {macro_dst}")

    with open(macro_dst) as fh:
        src = fh.read()

    old_inc = f'#include "{_HEADER_PLACEHOLDER}"'
    new_inc = f'#include "{os.path.abspath(header_path)}"'
    if old_inc in src:
        src = src.replace(old_inc, new_inc, 1)
        log(f"Patched include   : '{_HEADER_PLACEHOLDER}' -> {os.path.abspath(header_path)}")
    else:
        log(f"WARNING: placeholder '{old_inc}' not found in template.", "WARN")

    old_func = "void Run_EvtVtxZLeftRight_template("
    new_func = f"void {macro_name}("
    if old_func in src:
        src = src.replace(old_func, new_func, 1)
        log(f"Patched func name : 'Run_EvtVtxZLeftRight_template' -> '{macro_name}'")
    else:
        log("WARNING: function signature not found in template.", "WARN")

    with open(macro_dst, "w") as fh:
        fh.write(src)

    return macro_dst


def copy_and_patch_shell(cfg: EvtVtxZLeftRightConfig, out_dir: str) -> str:
    template_src = os.path.join(cfg.macro_template_dir, "run_job_template.sh")
    sh_dst = os.path.join(out_dir, f"run_job_{cfg.pass_name}.sh")

    if not os.path.isfile(template_src):
        raise FileNotFoundError(f"Shell template not found: {template_src}")

    with open(template_src) as f:
        src = f.read()
    src = src.replace("sphenix_setup.sh -n ana.538", f"sphenix_setup.sh -n {cfg.sphenix_build}")

    with open(sh_dst, "w") as f:
        f.write(src)
    os.chmod(sh_dst, 0o755)

    log(f"Copied shell      : {template_src}")
    log(f"             -> {sh_dst}")
    return sh_dst


def generate_condor_job(cfg: EvtVtxZLeftRightConfig, job_file_path: str,
                        macro_path: str, sh_path: str) -> str:
    macro_name = os.path.splitext(os.path.basename(macro_path))[0]
    gen_dir = os.path.dirname(macro_path)

    content = textwrap.dedent(f"""\
        Universe           = vanilla
        Initialdir         = {gen_dir}
        Executable         = {sh_path}
        PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
        concurrency_limits = CONCURRENCY_LIMIT_DEFAULT:{cfg.condor_concurrency_limit}
        request_memory     = {cfg.condor_request_memory}
        Priority           = {cfg.condor_priority}
        job_lease_duration = 86400

        runnumber          = {cfg.run_number}
        nEvents            = {cfg.n_events}
        input_directory    = {cfg.input_directory}
        job_offset         = {cfg.job_offset}
        process_shift      = $(Process) + $(job_offset)
        input_filename     = {_condor_input_filename(cfg)}
        output_directory   = {cfg.output_directory}
        macro_name         = {macro_name}

        Output             = $(output_directory)/cw_log/condor_$INT(process_shift,%05d).out
        Error              = $(output_directory)/cw_log/condor_$INT(process_shift,%05d).err
        Log                = $(output_directory)/cw_log/condor_$INT(process_shift,%05d).log
        Arguments          = "$INT(process_shift) $(runnumber) $(nEvents) $(output_directory) $(input_directory) $(input_filename) $(macro_name)"
        Queue {cfg.n_condor_jobs}
    """)

    Path(job_file_path).parent.mkdir(parents=True, exist_ok=True)
    with open(job_file_path, "w") as f:
        f.write(content)
    log(f"Wrote condor job  : {job_file_path}")
    return job_file_path


def run_cmd(cmd: str, dry: bool = False) -> int:
    log(f"  $ {cmd}")
    if dry:
        return 0
    result = subprocess.run(cmd, shell=True)
    return result.returncode


def validate_input_directory(cfg: EvtVtxZLeftRightConfig) -> None:
    if not os.path.isdir(cfg.input_directory):
        log(f"Input directory not found: {cfg.input_directory}", "ERR")
        log("Stop operation before generating files or submitting jobs.", "ERR")
        sys.exit(1)


def step_generate(cfg: EvtVtxZLeftRightConfig, dry: bool = False) -> None:
    log("-- Step 0: Generate files --------------------------------", "STEP")
    validate_input_directory(cfg)

    gen_dir = cfg.generated_dir()

    for d in [cfg.completed_dir(), cfg.condor_log_dir()]:
        if dry:
            log(f"[dry] Would create: {d}")
        else:
            Path(d).mkdir(parents=True, exist_ok=True)
            log(f"Ensured directory : {d}")

    if dry:
        macro_name = f"Run_EvtVtxZLeftRight_{cfg.pass_name}"
        log(f"[dry] Would generate header : {gen_dir}/{macro_name}_params.h")
        log(f"[dry] Would copy+patch macro -> {gen_dir}/{macro_name}.C")
        log(f"[dry] Would copy shell      -> {gen_dir}/run_job_{cfg.pass_name}.sh")
        log(f"[dry] Would write condor job: {gen_dir}/run_condor_{cfg.pass_name}.job")
        return

    hdr = generate_params_header(cfg, gen_dir)
    macro = copy_and_patch_macro(cfg, hdr, gen_dir)
    sh = copy_and_patch_shell(cfg, gen_dir)
    job_file = os.path.join(gen_dir, f"run_condor_{cfg.pass_name}.job")
    generate_condor_job(cfg, job_file, macro, sh)

    log("[STEP] File generation complete.")


def step_submit(cfg: EvtVtxZLeftRightConfig, dry: bool = False) -> None:
    step_generate(cfg, dry=dry)
    log("-- Step 1: Submit condor jobs -----------------------------", "STEP")
    job_file = os.path.join(cfg.generated_dir(), f"run_condor_{cfg.pass_name}.job")
    rc = run_cmd(f"condor_submit {job_file}", dry=dry)
    if rc != 0:
        log(f"condor_submit failed (exit {rc})", "ERR")
        sys.exit(rc)
    log("Jobs submitted successfully.")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="EvtVtxZLeftRight HTCondor pass orchestrator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent(__doc__),
    )
    parser.add_argument("config", help="Path to a config .py file (must define 'cfg').")
    parser.add_argument("--step", choices=["0", "1"], default="0",
                        help="0 = generate files only (default); 1 = generate + submit")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print what would be done without executing.")
    parser.add_argument("--set", metavar="VAR=VALUE", action="append", default=[],
                        help="Override a top-level config variable before loading.")

    args = parser.parse_args()

    if args.dry_run:
        log("DRY-RUN mode - no files will be written or submitted.", "WARN")

    cfg = load_config(args.config, parse_set_args(args.set) if args.set else None)
    print(cfg.summary())

    if args.step == "0":
        step_generate(cfg, dry=args.dry_run)
    elif args.step == "1":
        step_submit(cfg, dry=args.dry_run)


if __name__ == "__main__":
    main()
